[2024-12-19T21:45:28.752+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T21:45:28.771+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T21:39:28.868330+00:00 [queued]>
[2024-12-19T21:45:28.789+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T21:39:28.868330+00:00 [queued]>
[2024-12-19T21:45:28.790+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2024-12-19T21:45:28.813+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dashboard> on 2024-12-19 21:39:28.868330+00:00
[2024-12-19T21:45:28.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning:

This process (pid=437) is multi-threaded, use of fork() may lead to deadlocks in the child.


[2024-12-19T21:45:28.828+0000] {standard_task_runner.py:72} INFO - Started process 455 to run task
[2024-12-19T21:45:28.830+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'run_dashboard', 'manual__2024-12-19T21:39:28.868330+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpgcdxnfh0']
[2024-12-19T21:45:28.833+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask run_dashboard
[2024-12-19T21:45:28.920+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T21:39:28.868330+00:00 [running]> on host 3f9b1cd285db
[2024-12-19T21:45:29.117+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zeyad_Habash' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T21:39:28.868330+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T21:39:28.868330+00:00'
[2024-12-19T21:45:29.119+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T21:45:29.154+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T21:45:29.172+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'streamlit run /opt/***/dags/fintech_dashboard.py']
[2024-12-19T21:45:29.222+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T21:45:30.494+0000] {subprocess.py:106} INFO - 
[2024-12-19T21:45:30.495+0000] {subprocess.py:106} INFO - Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.
[2024-12-19T21:45:30.495+0000] {subprocess.py:106} INFO - 
[2024-12-19T21:45:31.068+0000] {subprocess.py:106} INFO - 
[2024-12-19T21:45:31.071+0000] {subprocess.py:106} INFO -   You can now view your Streamlit app in your browser.
[2024-12-19T21:45:31.074+0000] {subprocess.py:106} INFO - 
[2024-12-19T21:45:31.076+0000] {subprocess.py:106} INFO -   Local URL: http://localhost:8501
[2024-12-19T21:45:31.078+0000] {subprocess.py:106} INFO -   Network URL: http://172.18.0.6:8501
[2024-12-19T21:45:31.081+0000] {subprocess.py:106} INFO -   External URL: http://154.178.37.101:8501
[2024-12-19T21:45:31.084+0000] {subprocess.py:106} INFO - 
[2024-12-19T21:45:46.631+0000] {subprocess.py:106} INFO - 2024-12-19 21:45:46.623 Uncaught app execution
[2024-12-19T21:45:46.632+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-12-19T21:45:46.633+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
[2024-12-19T21:45:46.633+0000] {subprocess.py:106} INFO -     result = func()
[2024-12-19T21:45:46.634+0000] {subprocess.py:106} INFO -              ^^^^^^
[2024-12-19T21:45:46.634+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
[2024-12-19T21:45:46.635+0000] {subprocess.py:106} INFO -     exec(code, module.__dict__)
[2024-12-19T21:45:46.636+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/fintech_dashboard.py", line 133, in <module>
[2024-12-19T21:45:46.636+0000] {subprocess.py:106} INFO -     run_dashboard('./data/fintech_clean.parquet', './data/lookup_table.csv')
[2024-12-19T21:45:46.637+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/fintech_dashboard.py", line 119, in run_dashboard
[2024-12-19T21:45:46.637+0000] {subprocess.py:106} INFO -     df = pd.read_parquet(filename)
[2024-12-19T21:45:46.638+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-19T21:45:46.639+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
[2024-12-19T21:45:46.640+0000] {subprocess.py:106} INFO -     return impl.read(
[2024-12-19T21:45:46.641+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^
[2024-12-19T21:45:46.642+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
[2024-12-19T21:45:46.642+0000] {subprocess.py:106} INFO -     path_or_handle, handles, filesystem = _get_path_or_handle(
[2024-12-19T21:45:46.643+0000] {subprocess.py:106} INFO -                                           ^^^^^^^^^^^^^^^^^^^^
[2024-12-19T21:45:46.644+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
[2024-12-19T21:45:46.644+0000] {subprocess.py:106} INFO -     handles = get_handle(
[2024-12-19T21:45:46.645+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^^
[2024-12-19T21:45:46.645+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
[2024-12-19T21:45:46.646+0000] {subprocess.py:106} INFO -     handle = open(handle, ioargs.mode)
[2024-12-19T21:45:46.646+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-19T21:45:46.647+0000] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: './data/fintech_clean.parquet'
[2024-12-19T21:48:56.408+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-19T21:48:56.420+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-19T21:48:56.427+0000] {process_utils.py:132} INFO - Sending 15 to group 455. PIDs of all processes in the group: [457, 455]
[2024-12-19T21:48:56.428+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 455
[2024-12-19T21:48:56.429+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-19T21:48:56.437+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-12-19T21:48:56.475+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-19T21:48:56.501+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fintech_etl_pipeline, task_id=run_dashboard, run_id=manual__2024-12-19T21:39:28.868330+00:00, execution_date=20241219T213928, start_date=20241219T214528, end_date=20241219T214856
[2024-12-19T21:48:56.639+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T21:48:56.709+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=455, status='terminated', exitcode=2, started='21:45:28') (455) terminated with exit code 2
[2024-12-19T21:48:57.138+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=457, status='terminated', started='21:45:28') (457) terminated with exit code None
