[2024-12-19T23:08:02.473+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T23:08:02.495+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-19T23:07:48.511707+00:00 [queued]>
[2024-12-19T23:08:02.503+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-19T23:07:48.511707+00:00 [queued]>
[2024-12-19T23:08:02.504+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-19T23:08:02.618+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_db> on 2024-12-19 23:07:48.511707+00:00
[2024-12-19T23:08:02.627+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T23:08:02.630+0000] {standard_task_runner.py:72} INFO - Started process 138 to run task
[2024-12-19T23:08:02.630+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'load_to_db', 'manual__2024-12-19T23:07:48.511707+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmp4cwndtdc']
[2024-12-19T23:08:02.633+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask load_to_db
[2024-12-19T23:08:02.687+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-19T23:07:48.511707+00:00 [running]> on host bd82a0d94f0e
[2024-12-19T23:08:02.776+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zeyad_Habash' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T23:07:48.511707+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T23:07:48.511707+00:00'
[2024-12-19T23:08:02.778+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T23:08:03.397+0000] {logging_mixin.py:190} INFO - Connected to Database
[2024-12-19T23:08:03.398+0000] {logging_mixin.py:190} INFO - Writing cleaned dataset to database
[2024-12-19T23:08:03.438+0000] {logging_mixin.py:190} INFO - Cleaned Table fintech_data_MET_P1_52_16824 already exists.
[2024-12-19T23:08:03.441+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-19T23:08:03.453+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T23:08:03.454+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fintech_etl_pipeline, task_id=load_to_db, run_id=manual__2024-12-19T23:07:48.511707+00:00, execution_date=20241219T230748, start_date=20241219T230802, end_date=20241219T230803
[2024-12-19T23:08:03.494+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T23:08:03.538+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-19T23:08:03.542+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
