[2024-12-19T23:13:18.158+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T23:13:18.184+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T23:12:58.639369+00:00 [queued]>
[2024-12-19T23:13:18.194+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T23:12:58.639369+00:00 [queued]>
[2024-12-19T23:13:18.195+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-19T23:13:18.215+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dashboard> on 2024-12-19 23:12:58.639369+00:00
[2024-12-19T23:13:18.223+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T23:13:18.225+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2024-12-19T23:13:18.225+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'run_dashboard', 'manual__2024-12-19T23:12:58.639369+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmp8b_wxnpj']
[2024-12-19T23:13:18.228+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask run_dashboard
[2024-12-19T23:13:18.281+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T23:12:58.639369+00:00 [running]> on host b2048de23098
[2024-12-19T23:13:18.370+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zeyad_Habash' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T23:12:58.639369+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T23:12:58.639369+00:00'
[2024-12-19T23:13:18.371+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T23:13:18.385+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T23:13:18.386+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'streamlit run /opt/***/dags/fintech_dashboard.py -- --filename /opt/***/data/fintech_clean.parquet --lookup_table_filename /opt/***/data/lookup_table.csv']
[2024-12-19T23:13:18.400+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T23:13:19.588+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:13:19.589+0000] {subprocess.py:106} INFO - Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.
[2024-12-19T23:13:19.590+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:13:20.019+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:13:20.020+0000] {subprocess.py:106} INFO -   You can now view your Streamlit app in your browser.
[2024-12-19T23:13:20.020+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:13:20.022+0000] {subprocess.py:106} INFO -   Local URL: http://localhost:8501
[2024-12-19T23:13:20.024+0000] {subprocess.py:106} INFO -   Network URL: http://172.18.0.6:8501
[2024-12-19T23:13:20.027+0000] {subprocess.py:106} INFO -   External URL: http://154.178.37.101:8501
[2024-12-19T23:13:20.028+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:13:24.625+0000] {subprocess.py:106} INFO - usage: fintech_dashboard.py [-h] --filename FILENAME
[2024-12-19T23:13:24.626+0000] {subprocess.py:106} INFO - fintech_dashboard.py: error: unrecognized arguments: --lookup_table_filename /opt/***/data/lookup_table.csv
[2024-12-19T23:14:44.369+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-19T23:14:44.373+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-19T23:14:44.376+0000] {process_utils.py:132} INFO - Sending 15 to group 152. PIDs of all processes in the group: [154, 152]
[2024-12-19T23:14:44.377+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 152
[2024-12-19T23:14:44.379+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-19T23:14:44.381+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-12-19T23:14:44.423+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T23:14:44.471+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=152, status='terminated', exitcode=0, started='23:13:17') (152) terminated with exit code 0
[2024-12-19T23:14:44.686+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=154, status='terminated', started='23:13:17') (154) terminated with exit code None
